version: "3.5"

services:
  chat:
    command: mix phx.server
    env_file: .env
    build: .
    working_dir: /www/olc
    volumes:
      - .:/www/olc
    ports:
      - "4000:4000"
    links:
      - db

  db:
    image: postgres:12-alpine
    ports:
      - "5433:5432"
    env_file: .env
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data:
